### ISSUE TITLE
Photo gallery Page

### ISSUE THREAD

**Issue by techgurupezza** [techgurupezza/Play_Wilmington-Rails#42]
ability to group by album (Month and year) and user ability to upload

**Comment by techgurupezza** [comment]
- [ ] Add Back to album link above photos
- [ ] Add Lock down on Delete photo button
- [ ] Add Multi File Upload

**Comment by npezza93** [comment]
Good to go

**Comment by techgurupezza** [comment]
After loading more images the expand doesn't work

**Comment by npezza93** [comment]
Not anymore

**Comment by techgurupezza** [comment]
Will close and create new issue for deleting capabilities
