### ISSUE TITLE
Board of Directors

### ISSUE THREAD

**Issue by techgurupezza** [techgurupezza/Play_Wilmington-Rails#45]
add, edit, reorder, delete

Name, title, email, image

**Comment by npezza93** [comment]
Closing and updating #60

**Comment by techgurupezza** [comment]
Need to Remove Email Functionality from this one per Sam request

**Comment by techgurupezza** [comment]
Looks good need to remove the form field for email on board of directors as well

**Comment by npezza93** [comment]
done
