### ISSUE TITLE
Update the Panels on Home Page

### ISSUE THREAD

**Issue by techgurupezza** [techgurupezza/Play_Wilmington-Rails#56]
Update panel's on home page to use Materialize look and bring hours and Admissions down into there and expand first section (Hours/Admissions) by default

**Comment by npezza93** [comment]
Still need to do the hours and admissions sections

**Comment by techgurupezza** [comment]
oh good call

**Comment by npezza93** [comment]
Closing ticket and updating PR with what is to be tested.
