### ISSUE TITLE
Update Button Colors

### ISSUE THREAD

**Issue by techgurupezza** [techgurupezza/Play_Wilmington-Rails#58]
Update all Button classes for the edit screens to this:

`mdl-button mdl-js-button mdl-button--raised mdl-button--accent`

Helps the user see the button better and brings the blue on since it's the accent and not the orange

**Comment by npezza93** [comment]
Are there any I missed?

**Comment by techgurupezza** [comment]
Good as I see them I'll close and we can reopen if we find missing ones
