### ISSUE TITLE
Small UI Tweeks

### ISSUE THREAD

**Issue by techgurupezza** [techgurupezza/Play_Wilmington-Rails#65]
### Home Page
- [x] Update Safe Harbor Box on Home tab
- [x] Make Panels on home page go full width
- [x] Make Home Panel Text Editor `400px
- [x] Make "Create Home Section" title smaller (h1 to h4)
- [ ] Add Media CSS to Carousel 
- [x] Add Media CSS to Title in header instead of Truncate
- [x] update delete button on panels to have this class `mdl-button mdl-js-button mdl-button--icon mdl-button--accent`
- [x] Update Create new page to have label for Content
- [x] Update Links in footer to have `target: "_blank"`

### Plan Your Visit Pages
- [x]  Update edit & Delete button in Places to eat/Parking to be icons with this class on them `mdl-button mdl-js-button mdl-button--icon mdl-button--accent` 
- [x] Click close on map in Parking page on top of x to close popup
- [x] Change Title and Content Labels for FAQ to Question and Answer Labels respectfully.for Edit and new pages
- [x] Update title on NEW FAQ page to be "New FAQ Section"
- [x] Add Label for "Content textarea for FAQ new
- [x] Add Label to "Content" on new Parking/Eating page
- [x] Update Header for Parking/Food Edit to Be "Edit Food Section" or "Edit Parking Section"
- [x] Update New page header to be "New Parking/Eating Section"
- [x] Update Button label for Parking/eating Section to "Create Parking/Eating Marker"
- [x] add Class to Buttons on Faq panel buttons `mdl-button mdl-js-button mdl-button--icon mdl-button--accent`

### Exhibit Page
- [x] Update Edit page title to h4
- [x] update destroy button to "Delete" and add class `mdl-button mdl-js-button mdl-button--raised mdl-button--colored-red`
- [x] New Exhibit title to h4

### Outreach
- [x] change Edit outreach to h4
- [x] Update Outreach breaks

### About Us
- [x] Change our mission edit/Delete button to icons with this class `mdl-button mdl-js-button mdl-button--icon mdl-button--accent`
- [x] Change edit title to Editing Section or the actual tab name if possible
- [x] Change blog edit/Delete button to icons with this class `mdl-button mdl-js-button mdl-button--icon mdl-button--accent`
- [x] Add Ability to Edit Album Name
- [x] Update edit button class for edit photos to this `mdl-button mdl-js-button mdl-button--icon mdl-button--accent`
- [x] Change Fact Sheet edit/Delete button to icons with this class `mdl-button mdl-js-button mdl-button--icon mdl-button--accent`
- [x] Change Team edit/Delete button to icons with this class `mdl-button mdl-js-button mdl-button--icon mdl-button--accent`
- [x] Change team "X" to Trash can like everywhere else
- [x] Change Board edit/Delete button to icons with this class `mdl-button mdl-js-button mdl-button--icon mdl-button--accent`
- [x] Update New board page title to "New Board of Director Section"
- [x] Update New teams page title to "New Team Member Section"
- [ ] Ability to Edit Contact us panel incase info changes
- [ ] Ability to update Email dropdown for contact us if and email changes or they need to add a new one
- [x] Email Address from recipient in Contact Us Form

### Profile Page
- [x] put Current Password field First after email
- [x] change Password label to "New Password"

### Events and More
- [x] Fundraisers Page Breaks when click new
- [x]  Fundraiser Title to be uniform with Capitale starting letters
- [x]  Edit Fundraiser says New not Edit
- [x] add Class for Edit Delete button for Fundraiser page to match every where else `mdl-button mdl-js-button mdl-button--icon mdl-button--accent`

**Comment by techgurupezza** [comment]
This all looks good to be Will play by ear what gets in release and what doesnt make it we will create new ticket for and tag in Release #3

**Comment by npezza93** [comment]
### Home Page
- [ ] Add Media CSS to Carousel 
- [ ] Add Media CSS to Title in header instead of Truncate

### Plan Your Visit Pages
- [ ] Click close on map in Parking page on top of x to close popup

### About Us
- [x] Add Ability to Edit Album Name
- [ ] Update New board page title to "New Board of Director Section"
- [ ] Update New teams page title to "New Team Member Section"
- [ ] Ability to Edit Contact us panel incase info changes
- [ ] Ability to update Email dropdown for contact us if and email changes or they need to add a new one

### Events and More
- [ ]  Fundraiser Title to be uniform with Capitale starting letters


* updating so we know which ones are current

**Comment by techgurupezza** [comment]
sounds good and One more to add
### Home Page
- [ ] Update Links in footer to have `target: "_blank"`

**Comment by techgurupezza** [comment]
Fundraiser needs some tweaks check comment

**Comment by techgurupezza** [comment]
http://staging-cmow.herokuapp.com/exhibits 
Family Resource is cut off missing last word need to update font size...

**Comment by techgurupezza** [comment]
Going to Close and Create New issue to track 3 remaining for Release #3
